using Microsoft.VisualStudio.TestTools.UnitTesting;
using T4TS.Tests.Utils;

namespace T4TS.Tests.Fixtures.Options.Names
{
    [TestClass]
    public class Test
    {
        [TestMethod]
        public void NamesModelHasExpectedOutput()
        {
            // Expect
            new OutputFor(
                typeof(InterfaceNamePrefixModel),
                typeof(InterfaceNameOverrideModel),
                typeof(ModuleNameOverrideModel)
            ).ToEqual(ExpectedOutput);
        }

const string ExpectedOutput = @"
/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module SomeModule {
    /** Generated from T4TS.Tests.Fixtures.Options.Names.ModuleNameOverrideModel **/
    export interface Bar {
        SomeThirdProp: string;
    }
}

declare module T4TS {
    /** Generated from T4TS.Tests.Fixtures.Options.Names.InterfaceNamePrefixModel **/
    export interface FooInterfaceNamePrefixModel {
        SomeProp: string;
    }
    /** Generated from T4TS.Tests.Fixtures.Options.Names.InterfaceNameOverrideModel **/
    export interface Bar {
        SomeOtherProp: string;
    }
}
";
    }
}
