using Microsoft.VisualStudio.TestTools.UnitTesting;
using T4TS.Tests.Fixtures.Basic;
using T4TS.Tests.Utils;

namespace T4TS.Tests.Fixtures.Indexed
{
    [TestClass]
    public class Test
    {
        [TestMethod]
        public void IndexedModelHasExpectedOutput()
        {
            // Expect
            new OutputForAttributeBuilder(
                typeof(BasicModel),
                typeof(IndexedComplexModel),
                typeof(IndexedPrimitiveModel)
            ).ToEqual(ExpectedOutput);
        }

const string ExpectedOutput = 
@"/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS {
    /** Generated from T4TS.Tests.Fixtures.Basic.BasicModel */
    export interface BasicModel {
        MyProperty: number;
        SomeDateTime: string;
    }
    /** Generated from T4TS.Tests.Fixtures.Indexed.IndexedComplexModel */
    export interface IndexedComplexModel {
        SomeProp: number;
        [index: number]: T4TS.BasicModel;
    }
    /** Generated from T4TS.Tests.Fixtures.Indexed.IndexedPrimitiveModel */
    export interface IndexedPrimitiveModel {
        SomeProp: number;
        [index: number]: string;
    }
}
";
    }
}
