using Microsoft.VisualStudio.TestTools.UnitTesting;
using T4TS.Example.Models;
using T4TS.Tests.Fixtures.Basic;
using T4TS.Tests.Utils;

namespace T4TS.Tests.Fixtures.ExternalProp
{
    [TestClass]
    public class Test
    {
        [TestMethod]
        public void ExternalPropModelHasExpectedOutput()
        {
            // Expect
            new OutputForAttributeBuilder(
                typeof(ExternalPropModel),
                typeof(ModelFromDifferentProject),
                typeof(BasicModel)
            ).ToEqual(ExpectedOutput);
        }

const string ExpectedOutput =
@"/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module External {
    /** Generated from T4TS.Example.Models.ModelFromDifferentProject */
    export interface ModelFromDifferentProject {
        Id: number;
    }
}

declare module T4TS {
    /** Generated from T4TS.Tests.Fixtures.Basic.BasicModel */
    export interface BasicModel {
        MyProperty: number;
        SomeDateTime: string;
    }
    /** Generated from T4TS.Tests.Fixtures.ExternalProp.ExternalPropModel */
    export interface ExternalPropModel {
        Basic: T4TS.BasicModel;
        External: External.ModelFromDifferentProject;
    }
}
";

    }
}
