using System;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using T4TS.Tests.Utils;
using System.IO;
using System.Reflection;

namespace T4TS.Tests.Fixtures.Basic
{
    [TestClass]
    public class Test
    {
        [TestMethod]
        public void BasicModelHasExpectedOutput()
        {
            // Generated output
            var solution = DTETransformer.BuildDteSolution(typeof(Model));
            var settings = new Settings();
            var generator = new CodeTraverser(solution, settings);
            var data = generator.GetAllInterfaces().ToList();
            var generatedOutput = OutputFormatter.GetOutput(data, settings);
            
            const string expectedOutput =
@"/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS {
    /** Generated from T4TS.Tests.Fixtures.Basic.Model **/
    export interface Model {
        MyProperty: number;
    }
}
";

            Assert.AreEqual(expectedOutput, generatedOutput);
        }
    }
}
