using Microsoft.VisualStudio.TestTools.UnitTesting;
using T4TS.Tests.Utils;

namespace T4TS.Tests.Fixtures.Options.Default
{
    [TestClass]
    public class DefaultCamelCaseMemberNamesTest
    {
        [TestMethod]
        public void DefaultCamelCaseMemberNamesHasExpectedOutput()
        {
            // Expect
            new OutputForAttributeBuilder(
                typeof(DefaultCamelCaseMemberNamesModel),
                typeof(DefaultCamelCaseMemberNamesOverrideModel)
            ).With(new Settings {
                DefaultCamelCaseMemberNames = true
            }).ToEqual(ExpectedOutput);
        }

const string ExpectedOutput = 
@"/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS {
    /** Generated from T4TS.Tests.Fixtures.Options.Default.DefaultCamelCaseMemberNamesModel */
    export interface DefaultCamelCaseMemberNamesModel {
        someProp: string;
    }
    /** Generated from T4TS.Tests.Fixtures.Options.Default.DefaultCamelCaseMemberNamesOverrideModel */
    export interface DefaultCamelCaseMemberNamesOverrideModel {
        SomeProp: string;
    }
}
";
    }
}
