using Microsoft.VisualStudio.TestTools.UnitTesting;
using T4TS.Example.Models;
using T4TS.Tests.Fixtures.Basic;
using T4TS.Tests.Utils;

namespace T4TS.Tests.Fixtures.Generics
{
    [TestClass]
    public class Test
    {
        [TestMethod]
        public void GenericsExpectedOutput()
        {
            // Expect
            new OutputForDirectBuilder(
                typeof(GenericModel<System.String>).GetGenericTypeDefinition()
            ).ToEqual(ExpectedOutput);
        }

const string ExpectedOutput =
@"/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS.Tests.Fixtures.Generics {
    /** Generated from T4TS.Tests.Fixtures.Generics.GenericModel<TItem> **/
    export interface GenericModel<TItem> {
        Item: TItem;
        SomethingElse: number;
    }
}";

    }
}
